// SPDX-FileCopyrightText: 2026 Xquik contributors
//
// SPDX-License-Identifier: Apache-2.0

// File generated from our OpenAPI spec by Stainless.

package com.x_twitter_scraper.api.models

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.x_twitter_scraper.api.core.JsonValue
import com.x_twitter_scraper.api.core.jsonMapper
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class UserProfileTest {

    @Test
    fun create() {
        val userProfile =
            UserProfile.builder()
                .id("9876543210")
                .name("Elon Musk")
                .username("elonmusk")
                .affiliatesHighlightedLabel(
                    UserProfile.AffiliatesHighlightedLabel.builder()
                        .badgeUrl("badgeUrl")
                        .description("description")
                        .url("url")
                        .urlType("urlType")
                        .userLabelDisplayType("userLabelDisplayType")
                        .userLabelType("userLabelType")
                        .build()
                )
                .automatedBy("example_user")
                .businessAccountAffiliatesCount(0L)
                .communityRole("Member")
                .coverPicture("https://pbs.twimg.com/profile_banners/example.jpg")
                .createdAt("2009-06-02T20:12:29Z")
                .creatorSubscriptionsCount(0L)
                .description("CEO of Tesla, SpaceX, and X")
                .favouritesCount(18000L)
                .followers(150000000L)
                .following(500L)
                .hasCustomTimelines(true)
                .hasGraduatedAccess(true)
                .hasHiddenSubscriptionsOnProfile(true)
                .highlightsInfo(
                    UserProfile.HighlightsInfo.builder()
                        .canHighlightTweets(true)
                        .highlightedTweets("highlightedTweets")
                        .build()
                )
                .identityVerification(
                    UserProfile.IdentityVerification.builder()
                        .description("description")
                        .isIdentityVerified(true)
                        .verifiedSinceMsec("verifiedSinceMsec")
                        .build()
                )
                .isAutomated(false)
                .isBlueVerified(true)
                .isProfileTranslatable(true)
                .isTranslator(false)
                .isVerified(true)
                .location("Austin, TX")
                .mediaCount(1200L)
                .parodyCommentaryFanLabel("parodyCommentaryFanLabel")
                .addPinnedTweetId("1234567890")
                .possiblySensitive(false)
                .profileBio(
                    UserProfile.ProfileBio.builder()
                        .putAdditionalProperty("description", JsonValue.from("bar"))
                        .putAdditionalProperty("entities", JsonValue.from("bar"))
                        .build()
                )
                .profileBannerUrl("https://pbs.twimg.com/profile_banners/example.jpg")
                .profileDescriptionLanguage("profileDescriptionLanguage")
                .profileImageShape("profileImageShape")
                .profileInterstitialType("profileInterstitialType")
                .profilePicture("https://pbs.twimg.com/profile_images/example.jpg")
                .profileSortEnabled(true)
                .profileTranslatorType("profileTranslatorType")
                .protected_(false)
                .statusesCount(35000L)
                .superFollowEligible(true)
                .unavailable(false)
                .unavailableReason("suspended")
                .url("https://xquik.com")
                .verified(true)
                .verifiedType("Business")
                .addWithheldInCountry("DE")
                .build()

        assertThat(userProfile.id()).isEqualTo("9876543210")
        assertThat(userProfile.name()).isEqualTo("Elon Musk")
        assertThat(userProfile.username()).isEqualTo("elonmusk")
        assertThat(userProfile.affiliatesHighlightedLabel())
            .contains(
                UserProfile.AffiliatesHighlightedLabel.builder()
                    .badgeUrl("badgeUrl")
                    .description("description")
                    .url("url")
                    .urlType("urlType")
                    .userLabelDisplayType("userLabelDisplayType")
                    .userLabelType("userLabelType")
                    .build()
            )
        assertThat(userProfile.automatedBy()).contains("example_user")
        assertThat(userProfile.businessAccountAffiliatesCount()).contains(0L)
        assertThat(userProfile.communityRole()).contains("Member")
        assertThat(userProfile.coverPicture())
            .contains("https://pbs.twimg.com/profile_banners/example.jpg")
        assertThat(userProfile.createdAt()).contains("2009-06-02T20:12:29Z")
        assertThat(userProfile.creatorSubscriptionsCount()).contains(0L)
        assertThat(userProfile.description()).contains("CEO of Tesla, SpaceX, and X")
        assertThat(userProfile.favouritesCount()).contains(18000L)
        assertThat(userProfile.followers()).contains(150000000L)
        assertThat(userProfile.following()).contains(500L)
        assertThat(userProfile.hasCustomTimelines()).contains(true)
        assertThat(userProfile.hasGraduatedAccess()).contains(true)
        assertThat(userProfile.hasHiddenSubscriptionsOnProfile()).contains(true)
        assertThat(userProfile.highlightsInfo())
            .contains(
                UserProfile.HighlightsInfo.builder()
                    .canHighlightTweets(true)
                    .highlightedTweets("highlightedTweets")
                    .build()
            )
        assertThat(userProfile.identityVerification())
            .contains(
                UserProfile.IdentityVerification.builder()
                    .description("description")
                    .isIdentityVerified(true)
                    .verifiedSinceMsec("verifiedSinceMsec")
                    .build()
            )
        assertThat(userProfile.isAutomated()).contains(false)
        assertThat(userProfile.isBlueVerified()).contains(true)
        assertThat(userProfile.isProfileTranslatable()).contains(true)
        assertThat(userProfile.isTranslator()).contains(false)
        assertThat(userProfile.isVerified()).contains(true)
        assertThat(userProfile.location()).contains("Austin, TX")
        assertThat(userProfile.mediaCount()).contains(1200L)
        assertThat(userProfile.parodyCommentaryFanLabel()).contains("parodyCommentaryFanLabel")
        assertThat(userProfile.pinnedTweetIds().getOrNull()).containsExactly("1234567890")
        assertThat(userProfile.possiblySensitive()).contains(false)
        assertThat(userProfile.profileBio())
            .contains(
                UserProfile.ProfileBio.builder()
                    .putAdditionalProperty("description", JsonValue.from("bar"))
                    .putAdditionalProperty("entities", JsonValue.from("bar"))
                    .build()
            )
        assertThat(userProfile.profileBannerUrl())
            .contains("https://pbs.twimg.com/profile_banners/example.jpg")
        assertThat(userProfile.profileDescriptionLanguage()).contains("profileDescriptionLanguage")
        assertThat(userProfile.profileImageShape()).contains("profileImageShape")
        assertThat(userProfile.profileInterstitialType()).contains("profileInterstitialType")
        assertThat(userProfile.profilePicture())
            .contains("https://pbs.twimg.com/profile_images/example.jpg")
        assertThat(userProfile.profileSortEnabled()).contains(true)
        assertThat(userProfile.profileTranslatorType()).contains("profileTranslatorType")
        assertThat(userProfile.protected_()).contains(false)
        assertThat(userProfile.statusesCount()).contains(35000L)
        assertThat(userProfile.superFollowEligible()).contains(true)
        assertThat(userProfile.unavailable()).contains(false)
        assertThat(userProfile.unavailableReason()).contains("suspended")
        assertThat(userProfile.url()).contains("https://xquik.com")
        assertThat(userProfile.verified()).contains(true)
        assertThat(userProfile.verifiedType()).contains("Business")
        assertThat(userProfile.withheldInCountries().getOrNull()).containsExactly("DE")
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val userProfile =
            UserProfile.builder()
                .id("9876543210")
                .name("Elon Musk")
                .username("elonmusk")
                .affiliatesHighlightedLabel(
                    UserProfile.AffiliatesHighlightedLabel.builder()
                        .badgeUrl("badgeUrl")
                        .description("description")
                        .url("url")
                        .urlType("urlType")
                        .userLabelDisplayType("userLabelDisplayType")
                        .userLabelType("userLabelType")
                        .build()
                )
                .automatedBy("example_user")
                .businessAccountAffiliatesCount(0L)
                .communityRole("Member")
                .coverPicture("https://pbs.twimg.com/profile_banners/example.jpg")
                .createdAt("2009-06-02T20:12:29Z")
                .creatorSubscriptionsCount(0L)
                .description("CEO of Tesla, SpaceX, and X")
                .favouritesCount(18000L)
                .followers(150000000L)
                .following(500L)
                .hasCustomTimelines(true)
                .hasGraduatedAccess(true)
                .hasHiddenSubscriptionsOnProfile(true)
                .highlightsInfo(
                    UserProfile.HighlightsInfo.builder()
                        .canHighlightTweets(true)
                        .highlightedTweets("highlightedTweets")
                        .build()
                )
                .identityVerification(
                    UserProfile.IdentityVerification.builder()
                        .description("description")
                        .isIdentityVerified(true)
                        .verifiedSinceMsec("verifiedSinceMsec")
                        .build()
                )
                .isAutomated(false)
                .isBlueVerified(true)
                .isProfileTranslatable(true)
                .isTranslator(false)
                .isVerified(true)
                .location("Austin, TX")
                .mediaCount(1200L)
                .parodyCommentaryFanLabel("parodyCommentaryFanLabel")
                .addPinnedTweetId("1234567890")
                .possiblySensitive(false)
                .profileBio(
                    UserProfile.ProfileBio.builder()
                        .putAdditionalProperty("description", JsonValue.from("bar"))
                        .putAdditionalProperty("entities", JsonValue.from("bar"))
                        .build()
                )
                .profileBannerUrl("https://pbs.twimg.com/profile_banners/example.jpg")
                .profileDescriptionLanguage("profileDescriptionLanguage")
                .profileImageShape("profileImageShape")
                .profileInterstitialType("profileInterstitialType")
                .profilePicture("https://pbs.twimg.com/profile_images/example.jpg")
                .profileSortEnabled(true)
                .profileTranslatorType("profileTranslatorType")
                .protected_(false)
                .statusesCount(35000L)
                .superFollowEligible(true)
                .unavailable(false)
                .unavailableReason("suspended")
                .url("https://xquik.com")
                .verified(true)
                .verifiedType("Business")
                .addWithheldInCountry("DE")
                .build()

        val roundtrippedUserProfile =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(userProfile),
                jacksonTypeRef<UserProfile>(),
            )

        assertThat(roundtrippedUserProfile).isEqualTo(userProfile)
    }
}
