// SPDX-FileCopyrightText: 2026 Xquik contributors
//
// SPDX-License-Identifier: Apache-2.0

// File generated from our OpenAPI spec by Stainless.

package com.x_twitter_scraper.api.models.x.writeactions

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.x_twitter_scraper.api.core.JsonValue
import com.x_twitter_scraper.api.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class WriteActionRetrieveResponseTest {

    @Test
    fun create() {
        val writeActionRetrieveResponse =
            WriteActionRetrieveResponse.builder()
                .id("12345")
                .account(
                    WriteActionRetrieveResponse.Account.builder()
                        .id("42")
                        .username("example")
                        .build()
                )
                .action(WriteActionRetrieveResponse.Action.LIKE)
                .billing(
                    WriteActionRetrieveResponse.Billing.builder()
                        .charged(true)
                        .chargedCredits("10")
                        .plannedCredits("10")
                        .status(WriteActionRetrieveResponse.Billing.Status.CHARGED)
                        .build()
                )
                .charged(true)
                .chargedCredits("10")
                .nextAction(
                    WriteActionRetrieveResponse.NextAction.builder()
                        .type(WriteActionRetrieveResponse.NextAction.Type.POLL)
                        .afterMs(2000L)
                        .requiresNewIdempotencyKey(true)
                        .url("/api/v1/x/write-actions/12345")
                        .build()
                )
                .pollAfterMs(null)
                .request(
                    WriteActionRetrieveResponse.Request.builder()
                        .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                        .payload(
                            WriteActionRetrieveResponse.Request.Payload.builder()
                                .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .result(
                    WriteActionRetrieveResponse.Result.builder()
                        .id("9876543210")
                        .state("liked")
                        .type(WriteActionRetrieveResponse.Result.Type.STATE_CHANGE)
                        .build()
                )
                .retryable(false)
                .safeToRetry(false)
                .sendDispatched(true)
                .status(WriteActionRetrieveResponse.Status.SUCCESS)
                .statusUrl("/api/v1/x/write-actions/12345")
                .success(true)
                .target(
                    WriteActionRetrieveResponse.Target.builder()
                        .id("9876543210")
                        .type(WriteActionRetrieveResponse.Target.Type.TWEET)
                        .build()
                )
                .targetId("9876543210")
                .terminal(true)
                .writeActionId("12345")
                .communityId("3456789012")
                .communityName("Builders")
                .completedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmationAttempts(1L)
                .confirmationCheckedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .createdAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .details(
                    WriteActionRetrieveResponse.Details.builder()
                        .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                        .build()
                )
                .error("x_write_ambiguous")
                .expiresAt(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
                .idempotent(false)
                .media(
                    WriteActionRetrieveResponse.Media.builder()
                        .putAdditionalProperty("count", JsonValue.from("bar"))
                        .putAdditionalProperty("kind", JsonValue.from("bar"))
                        .build()
                )
                .mediaId("2345678901")
                .mediaUrl("https://media.xquik.com/example.jpg")
                .message("Invalid input. Check request fields.")
                .messageId("1234567890")
                .requestHash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                .requestId("01JZ8R7QSC9QKT0V7JX4M2A6B8")
                .resultId("9876543210")
                .sendDispatchedAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .tweetId("9876543210")
                .updatedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .build()

        assertThat(writeActionRetrieveResponse.id()).isEqualTo("12345")
        assertThat(writeActionRetrieveResponse.account())
            .contains(
                WriteActionRetrieveResponse.Account.builder().id("42").username("example").build()
            )
        assertThat(writeActionRetrieveResponse.action())
            .isEqualTo(WriteActionRetrieveResponse.Action.LIKE)
        assertThat(writeActionRetrieveResponse.billing())
            .isEqualTo(
                WriteActionRetrieveResponse.Billing.builder()
                    .charged(true)
                    .chargedCredits("10")
                    .plannedCredits("10")
                    .status(WriteActionRetrieveResponse.Billing.Status.CHARGED)
                    .build()
            )
        assertThat(writeActionRetrieveResponse.charged()).isEqualTo(true)
        assertThat(writeActionRetrieveResponse.chargedCredits()).isEqualTo("10")
        assertThat(writeActionRetrieveResponse.nextAction())
            .contains(
                WriteActionRetrieveResponse.NextAction.builder()
                    .type(WriteActionRetrieveResponse.NextAction.Type.POLL)
                    .afterMs(2000L)
                    .requiresNewIdempotencyKey(true)
                    .url("/api/v1/x/write-actions/12345")
                    .build()
            )
        assertThat(writeActionRetrieveResponse.pollAfterMs()).isEmpty
        assertThat(writeActionRetrieveResponse.request())
            .isEqualTo(
                WriteActionRetrieveResponse.Request.builder()
                    .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                    .payload(
                        WriteActionRetrieveResponse.Request.Payload.builder()
                            .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                            .build()
                    )
                    .build()
            )
        assertThat(writeActionRetrieveResponse.result())
            .contains(
                WriteActionRetrieveResponse.Result.builder()
                    .id("9876543210")
                    .state("liked")
                    .type(WriteActionRetrieveResponse.Result.Type.STATE_CHANGE)
                    .build()
            )
        assertThat(writeActionRetrieveResponse.retryable()).isEqualTo(false)
        assertThat(writeActionRetrieveResponse.safeToRetry()).isEqualTo(false)
        assertThat(writeActionRetrieveResponse.sendDispatched()).isEqualTo(true)
        assertThat(writeActionRetrieveResponse.status())
            .isEqualTo(WriteActionRetrieveResponse.Status.SUCCESS)
        assertThat(writeActionRetrieveResponse.statusUrl())
            .isEqualTo("/api/v1/x/write-actions/12345")
        assertThat(writeActionRetrieveResponse.success()).isEqualTo(true)
        assertThat(writeActionRetrieveResponse.target())
            .contains(
                WriteActionRetrieveResponse.Target.builder()
                    .id("9876543210")
                    .type(WriteActionRetrieveResponse.Target.Type.TWEET)
                    .build()
            )
        assertThat(writeActionRetrieveResponse.targetId()).contains("9876543210")
        assertThat(writeActionRetrieveResponse.terminal()).isEqualTo(true)
        assertThat(writeActionRetrieveResponse.writeActionId()).isEqualTo("12345")
        assertThat(writeActionRetrieveResponse.communityId()).contains("3456789012")
        assertThat(writeActionRetrieveResponse.communityName()).contains("Builders")
        assertThat(writeActionRetrieveResponse.completedAt())
            .contains(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(writeActionRetrieveResponse.confirmationAttempts()).contains(1L)
        assertThat(writeActionRetrieveResponse.confirmationCheckedAt())
            .contains(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(writeActionRetrieveResponse.confirmedAt())
            .contains(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(writeActionRetrieveResponse.createdAt())
            .contains(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
        assertThat(writeActionRetrieveResponse.details())
            .contains(
                WriteActionRetrieveResponse.Details.builder()
                    .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                    .build()
            )
        assertThat(writeActionRetrieveResponse.error()).contains("x_write_ambiguous")
        assertThat(writeActionRetrieveResponse.expiresAt())
            .contains(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
        assertThat(writeActionRetrieveResponse.idempotent()).contains(false)
        assertThat(writeActionRetrieveResponse.media())
            .contains(
                WriteActionRetrieveResponse.Media.builder()
                    .putAdditionalProperty("count", JsonValue.from("bar"))
                    .putAdditionalProperty("kind", JsonValue.from("bar"))
                    .build()
            )
        assertThat(writeActionRetrieveResponse.mediaId()).contains("2345678901")
        assertThat(writeActionRetrieveResponse.mediaUrl())
            .contains("https://media.xquik.com/example.jpg")
        assertThat(writeActionRetrieveResponse.message())
            .contains("Invalid input. Check request fields.")
        assertThat(writeActionRetrieveResponse.messageId()).contains("1234567890")
        assertThat(writeActionRetrieveResponse.requestHash())
            .contains("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
        assertThat(writeActionRetrieveResponse.requestId()).contains("01JZ8R7QSC9QKT0V7JX4M2A6B8")
        assertThat(writeActionRetrieveResponse.resultId()).contains("9876543210")
        assertThat(writeActionRetrieveResponse.sendDispatchedAt())
            .contains(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
        assertThat(writeActionRetrieveResponse.tweetId()).contains("9876543210")
        assertThat(writeActionRetrieveResponse.updatedAt())
            .contains(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val writeActionRetrieveResponse =
            WriteActionRetrieveResponse.builder()
                .id("12345")
                .account(
                    WriteActionRetrieveResponse.Account.builder()
                        .id("42")
                        .username("example")
                        .build()
                )
                .action(WriteActionRetrieveResponse.Action.LIKE)
                .billing(
                    WriteActionRetrieveResponse.Billing.builder()
                        .charged(true)
                        .chargedCredits("10")
                        .plannedCredits("10")
                        .status(WriteActionRetrieveResponse.Billing.Status.CHARGED)
                        .build()
                )
                .charged(true)
                .chargedCredits("10")
                .nextAction(
                    WriteActionRetrieveResponse.NextAction.builder()
                        .type(WriteActionRetrieveResponse.NextAction.Type.POLL)
                        .afterMs(2000L)
                        .requiresNewIdempotencyKey(true)
                        .url("/api/v1/x/write-actions/12345")
                        .build()
                )
                .pollAfterMs(null)
                .request(
                    WriteActionRetrieveResponse.Request.builder()
                        .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                        .payload(
                            WriteActionRetrieveResponse.Request.Payload.builder()
                                .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .result(
                    WriteActionRetrieveResponse.Result.builder()
                        .id("9876543210")
                        .state("liked")
                        .type(WriteActionRetrieveResponse.Result.Type.STATE_CHANGE)
                        .build()
                )
                .retryable(false)
                .safeToRetry(false)
                .sendDispatched(true)
                .status(WriteActionRetrieveResponse.Status.SUCCESS)
                .statusUrl("/api/v1/x/write-actions/12345")
                .success(true)
                .target(
                    WriteActionRetrieveResponse.Target.builder()
                        .id("9876543210")
                        .type(WriteActionRetrieveResponse.Target.Type.TWEET)
                        .build()
                )
                .targetId("9876543210")
                .terminal(true)
                .writeActionId("12345")
                .communityId("3456789012")
                .communityName("Builders")
                .completedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmationAttempts(1L)
                .confirmationCheckedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .createdAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .details(
                    WriteActionRetrieveResponse.Details.builder()
                        .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                        .build()
                )
                .error("x_write_ambiguous")
                .expiresAt(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
                .idempotent(false)
                .media(
                    WriteActionRetrieveResponse.Media.builder()
                        .putAdditionalProperty("count", JsonValue.from("bar"))
                        .putAdditionalProperty("kind", JsonValue.from("bar"))
                        .build()
                )
                .mediaId("2345678901")
                .mediaUrl("https://media.xquik.com/example.jpg")
                .message("Invalid input. Check request fields.")
                .messageId("1234567890")
                .requestHash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                .requestId("01JZ8R7QSC9QKT0V7JX4M2A6B8")
                .resultId("9876543210")
                .sendDispatchedAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .tweetId("9876543210")
                .updatedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .build()

        val roundtrippedWriteActionRetrieveResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(writeActionRetrieveResponse),
                jacksonTypeRef<WriteActionRetrieveResponse>(),
            )

        assertThat(roundtrippedWriteActionRetrieveResponse).isEqualTo(writeActionRetrieveResponse)
    }
}
