// File generated from our OpenAPI spec by Stainless.

package com.x_twitter_scraper.api.models.x.communities

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.x_twitter_scraper.api.core.JsonValue
import com.x_twitter_scraper.api.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class CommunityCreateResponseTest {

    @Test
    fun create() {
        val communityCreateResponse =
            CommunityCreateResponse.builder()
                .id("12345")
                .account(
                    CommunityCreateResponse.Account.builder().id("42").username("example").build()
                )
                .action(CommunityCreateResponse.Action.LIKE)
                .billing(
                    CommunityCreateResponse.Billing.builder()
                        .charged(true)
                        .chargedCredits("10")
                        .plannedCredits("10")
                        .status(CommunityCreateResponse.Billing.Status.CHARGED)
                        .build()
                )
                .charged(true)
                .chargedCredits("10")
                .nextAction(
                    CommunityCreateResponse.NextAction.builder()
                        .type(CommunityCreateResponse.NextAction.Type.POLL)
                        .afterMs(2000L)
                        .requiresNewIdempotencyKey(true)
                        .url("/api/v1/x/write-actions/12345")
                        .build()
                )
                .pollAfterMs(null)
                .request(
                    CommunityCreateResponse.Request.builder()
                        .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                        .payload(
                            CommunityCreateResponse.Request.Payload.builder()
                                .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .result(
                    CommunityCreateResponse.Result.builder()
                        .id("9876543210")
                        .state("liked")
                        .type(CommunityCreateResponse.Result.Type.STATE_CHANGE)
                        .build()
                )
                .retryable(false)
                .safeToRetry(false)
                .sendDispatched(true)
                .status(CommunityCreateResponse.Status.SUCCESS)
                .statusUrl("/api/v1/x/write-actions/12345")
                .success(true)
                .target(
                    CommunityCreateResponse.Target.builder()
                        .id("9876543210")
                        .type(CommunityCreateResponse.Target.Type.TWEET)
                        .build()
                )
                .targetId("9876543210")
                .terminal(true)
                .writeActionId("12345")
                .communityId("3456789012")
                .communityName("Builders")
                .completedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmationAttempts(1L)
                .confirmationCheckedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .createdAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .details(
                    CommunityCreateResponse.Details.builder()
                        .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                        .build()
                )
                .error("x_write_ambiguous")
                .expiresAt(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
                .idempotent(false)
                .media(
                    CommunityCreateResponse.Media.builder()
                        .putAdditionalProperty("count", JsonValue.from("bar"))
                        .putAdditionalProperty("kind", JsonValue.from("bar"))
                        .build()
                )
                .mediaId("2345678901")
                .mediaUrl("https://media.xquik.com/example.jpg")
                .message("Invalid input. Check request fields.")
                .messageId("1234567890")
                .requestHash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                .requestId("01JZ8R7QSC9QKT0V7JX4M2A6B8")
                .resultId("9876543210")
                .sendDispatchedAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .tweetId("9876543210")
                .updatedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .build()

        assertThat(communityCreateResponse.id()).isEqualTo("12345")
        assertThat(communityCreateResponse.account())
            .contains(
                CommunityCreateResponse.Account.builder().id("42").username("example").build()
            )
        assertThat(communityCreateResponse.action()).isEqualTo(CommunityCreateResponse.Action.LIKE)
        assertThat(communityCreateResponse.billing())
            .isEqualTo(
                CommunityCreateResponse.Billing.builder()
                    .charged(true)
                    .chargedCredits("10")
                    .plannedCredits("10")
                    .status(CommunityCreateResponse.Billing.Status.CHARGED)
                    .build()
            )
        assertThat(communityCreateResponse.charged()).isEqualTo(true)
        assertThat(communityCreateResponse.chargedCredits()).isEqualTo("10")
        assertThat(communityCreateResponse.nextAction())
            .contains(
                CommunityCreateResponse.NextAction.builder()
                    .type(CommunityCreateResponse.NextAction.Type.POLL)
                    .afterMs(2000L)
                    .requiresNewIdempotencyKey(true)
                    .url("/api/v1/x/write-actions/12345")
                    .build()
            )
        assertThat(communityCreateResponse.pollAfterMs()).isEmpty
        assertThat(communityCreateResponse.request())
            .isEqualTo(
                CommunityCreateResponse.Request.builder()
                    .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                    .payload(
                        CommunityCreateResponse.Request.Payload.builder()
                            .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                            .build()
                    )
                    .build()
            )
        assertThat(communityCreateResponse.result())
            .contains(
                CommunityCreateResponse.Result.builder()
                    .id("9876543210")
                    .state("liked")
                    .type(CommunityCreateResponse.Result.Type.STATE_CHANGE)
                    .build()
            )
        assertThat(communityCreateResponse.retryable()).isEqualTo(false)
        assertThat(communityCreateResponse.safeToRetry()).isEqualTo(false)
        assertThat(communityCreateResponse.sendDispatched()).isEqualTo(true)
        assertThat(communityCreateResponse.status())
            .isEqualTo(CommunityCreateResponse.Status.SUCCESS)
        assertThat(communityCreateResponse.statusUrl()).isEqualTo("/api/v1/x/write-actions/12345")
        assertThat(communityCreateResponse.success()).isEqualTo(true)
        assertThat(communityCreateResponse.target())
            .contains(
                CommunityCreateResponse.Target.builder()
                    .id("9876543210")
                    .type(CommunityCreateResponse.Target.Type.TWEET)
                    .build()
            )
        assertThat(communityCreateResponse.targetId()).contains("9876543210")
        assertThat(communityCreateResponse.terminal()).isEqualTo(true)
        assertThat(communityCreateResponse.writeActionId()).isEqualTo("12345")
        assertThat(communityCreateResponse.communityId()).contains("3456789012")
        assertThat(communityCreateResponse.communityName()).contains("Builders")
        assertThat(communityCreateResponse.completedAt())
            .contains(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(communityCreateResponse.confirmationAttempts()).contains(1L)
        assertThat(communityCreateResponse.confirmationCheckedAt())
            .contains(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(communityCreateResponse.confirmedAt())
            .contains(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(communityCreateResponse.createdAt())
            .contains(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
        assertThat(communityCreateResponse.details())
            .contains(
                CommunityCreateResponse.Details.builder()
                    .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                    .build()
            )
        assertThat(communityCreateResponse.error()).contains("x_write_ambiguous")
        assertThat(communityCreateResponse.expiresAt())
            .contains(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
        assertThat(communityCreateResponse.idempotent()).contains(false)
        assertThat(communityCreateResponse.media())
            .contains(
                CommunityCreateResponse.Media.builder()
                    .putAdditionalProperty("count", JsonValue.from("bar"))
                    .putAdditionalProperty("kind", JsonValue.from("bar"))
                    .build()
            )
        assertThat(communityCreateResponse.mediaId()).contains("2345678901")
        assertThat(communityCreateResponse.mediaUrl())
            .contains("https://media.xquik.com/example.jpg")
        assertThat(communityCreateResponse.message())
            .contains("Invalid input. Check request fields.")
        assertThat(communityCreateResponse.messageId()).contains("1234567890")
        assertThat(communityCreateResponse.requestHash())
            .contains("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
        assertThat(communityCreateResponse.requestId()).contains("01JZ8R7QSC9QKT0V7JX4M2A6B8")
        assertThat(communityCreateResponse.resultId()).contains("9876543210")
        assertThat(communityCreateResponse.sendDispatchedAt())
            .contains(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
        assertThat(communityCreateResponse.tweetId()).contains("9876543210")
        assertThat(communityCreateResponse.updatedAt())
            .contains(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val communityCreateResponse =
            CommunityCreateResponse.builder()
                .id("12345")
                .account(
                    CommunityCreateResponse.Account.builder().id("42").username("example").build()
                )
                .action(CommunityCreateResponse.Action.LIKE)
                .billing(
                    CommunityCreateResponse.Billing.builder()
                        .charged(true)
                        .chargedCredits("10")
                        .plannedCredits("10")
                        .status(CommunityCreateResponse.Billing.Status.CHARGED)
                        .build()
                )
                .charged(true)
                .chargedCredits("10")
                .nextAction(
                    CommunityCreateResponse.NextAction.builder()
                        .type(CommunityCreateResponse.NextAction.Type.POLL)
                        .afterMs(2000L)
                        .requiresNewIdempotencyKey(true)
                        .url("/api/v1/x/write-actions/12345")
                        .build()
                )
                .pollAfterMs(null)
                .request(
                    CommunityCreateResponse.Request.builder()
                        .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                        .payload(
                            CommunityCreateResponse.Request.Payload.builder()
                                .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .result(
                    CommunityCreateResponse.Result.builder()
                        .id("9876543210")
                        .state("liked")
                        .type(CommunityCreateResponse.Result.Type.STATE_CHANGE)
                        .build()
                )
                .retryable(false)
                .safeToRetry(false)
                .sendDispatched(true)
                .status(CommunityCreateResponse.Status.SUCCESS)
                .statusUrl("/api/v1/x/write-actions/12345")
                .success(true)
                .target(
                    CommunityCreateResponse.Target.builder()
                        .id("9876543210")
                        .type(CommunityCreateResponse.Target.Type.TWEET)
                        .build()
                )
                .targetId("9876543210")
                .terminal(true)
                .writeActionId("12345")
                .communityId("3456789012")
                .communityName("Builders")
                .completedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmationAttempts(1L)
                .confirmationCheckedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .createdAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .details(
                    CommunityCreateResponse.Details.builder()
                        .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                        .build()
                )
                .error("x_write_ambiguous")
                .expiresAt(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
                .idempotent(false)
                .media(
                    CommunityCreateResponse.Media.builder()
                        .putAdditionalProperty("count", JsonValue.from("bar"))
                        .putAdditionalProperty("kind", JsonValue.from("bar"))
                        .build()
                )
                .mediaId("2345678901")
                .mediaUrl("https://media.xquik.com/example.jpg")
                .message("Invalid input. Check request fields.")
                .messageId("1234567890")
                .requestHash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                .requestId("01JZ8R7QSC9QKT0V7JX4M2A6B8")
                .resultId("9876543210")
                .sendDispatchedAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .tweetId("9876543210")
                .updatedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .build()

        val roundtrippedCommunityCreateResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(communityCreateResponse),
                jacksonTypeRef<CommunityCreateResponse>(),
            )

        assertThat(roundtrippedCommunityCreateResponse).isEqualTo(communityCreateResponse)
    }
}
