// SPDX-FileCopyrightText: 2026 Xquik contributors
//
// SPDX-License-Identifier: Apache-2.0

// File generated from our OpenAPI spec by Stainless.

package com.x_twitter_scraper.api.models.extractions

import java.time.LocalDate
import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class ExtractionEstimateCostParamsTest {

    @Test
    fun create() {
        ExtractionEstimateCostParams.builder()
            .toolType(ExtractionEstimateCostParams.ToolType.FOLLOWER_EXPLORER)
            .advancedQuery("min_faves:100")
            .anyWords("ChatGPT AI model")
            .bioContains("bioContains")
            .blueVerifiedOnly(true)
            .boundingBox("-74.1 40.6 -73.9 40.8")
            .cardName("cardName")
            .cashtags("\$TSLA \$NVDA")
            .collectionStrategy(ExtractionEstimateCostParams.CollectionStrategy.AUTO)
            .conversationId("1234567890")
            .dedupeAcrossTargets(true)
            .dedupeMode(ExtractionEstimateCostParams.DedupeMode.NONE)
            .exactPhrase("artificial intelligence")
            .excludeOriginalAuthor(true)
            .excludeSource("excludeSource")
            .excludeWords("spam")
            .fromUser("nasa")
            .geocode("geocode")
            .hashtags("#AI startups")
            .hasLocation(true)
            .hasMediaOnly(true)
            .hasWebsite(true)
            .includeOriginalPost(true)
            .includeSearchTerms(true)
            .includeTargetMetadata(true)
            .inReplyToTweetId("1234567890")
            .language("en")
            .listId("1234567890")
            .locationContains("locationContains")
            .maxDepth(1L)
            .maxFollowers(0L)
            .maxFollowing(0L)
            .maxId("maxId")
            .maxItemsPerTarget(1L)
            .maxLikes(0L)
            .maxPagesPerTarget(1L)
            .maxPosts(0L)
            .maxQuotes(0L)
            .maxReplies(0L)
            .maxRetweets(0L)
            .mediaType(ExtractionEstimateCostParams.MediaType.IMAGES)
            .mentioning("example_user")
            .minAccountAgeDays(0L)
            .minBookmarks(0L)
            .minFaves(10L)
            .minFollowers(0L)
            .minFollowing(0L)
            .minPosts(0L)
            .minQuotes(2L)
            .minReplies(3L)
            .minRetweets(5L)
            .minViews(0L)
            .nativeRetweets(true)
            .near("near")
            .news(true)
            .overlapMode(true)
            .place("96683cc9126741d1")
            .placeCountry("US")
            .pointRadius("-73.99 40.73 25mi")
            .queryType(ExtractionEstimateCostParams.QueryType.LATEST)
            .quotes(ExtractionEstimateCostParams.Quotes.INCLUDE)
            .quotesOfTweetId("1234567890")
            .addRelationTarget(
                ExtractionEstimateCostParams.RelationTarget.builder()
                    .relation(
                        ExtractionEstimateCostParams.RelationTarget.Relation.COMMUNITY_MEMBERS
                    )
                    .value("x")
                    .build()
            )
            .replies(ExtractionEstimateCostParams.Replies.INCLUDE)
            .resultsLimit(1000L)
            .retweets(ExtractionEstimateCostParams.Retweets.EXCLUDE)
            .retweetsOfTweetId("1234567890")
            .safe(true)
            .scope(ExtractionEstimateCostParams.Scope.ALL)
            .addSearchQuery("string")
            .searchQuery("AI trends 2025")
            .sinceDate(LocalDate.parse("2025-01-01"))
            .sinceId("sinceId")
            .sinceTime(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
            .sort(ExtractionEstimateCostParams.Sort.RELEVANCE)
            .source("source")
            .startCursor("x")
            .targetCommunityId("1500000000000000000")
            .addTargetCommunityId("string")
            .targetListId("1234567890")
            .addTargetListId("string")
            .addTarget("string")
            .targetSpaceId("1vOGwMdBqpwGB")
            .targetTweetId("1234567890")
            .addTargetTweetId("string")
            .targetUsername("elonmusk")
            .addTargetUsername("string")
            .toUser("openai")
            .untilDate(LocalDate.parse("2025-12-31"))
            .untilTime(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
            .url("example.com")
            .usernameContains("usernameContains")
            .verifiedOnly(false)
            .verifiedType("verifiedType")
            .within("within")
            .withinTime("withinTime")
            .build()
    }

    @Test
    fun body() {
        val params =
            ExtractionEstimateCostParams.builder()
                .toolType(ExtractionEstimateCostParams.ToolType.FOLLOWER_EXPLORER)
                .advancedQuery("min_faves:100")
                .anyWords("ChatGPT AI model")
                .bioContains("bioContains")
                .blueVerifiedOnly(true)
                .boundingBox("-74.1 40.6 -73.9 40.8")
                .cardName("cardName")
                .cashtags("\$TSLA \$NVDA")
                .collectionStrategy(ExtractionEstimateCostParams.CollectionStrategy.AUTO)
                .conversationId("1234567890")
                .dedupeAcrossTargets(true)
                .dedupeMode(ExtractionEstimateCostParams.DedupeMode.NONE)
                .exactPhrase("artificial intelligence")
                .excludeOriginalAuthor(true)
                .excludeSource("excludeSource")
                .excludeWords("spam")
                .fromUser("nasa")
                .geocode("geocode")
                .hashtags("#AI startups")
                .hasLocation(true)
                .hasMediaOnly(true)
                .hasWebsite(true)
                .includeOriginalPost(true)
                .includeSearchTerms(true)
                .includeTargetMetadata(true)
                .inReplyToTweetId("1234567890")
                .language("en")
                .listId("1234567890")
                .locationContains("locationContains")
                .maxDepth(1L)
                .maxFollowers(0L)
                .maxFollowing(0L)
                .maxId("maxId")
                .maxItemsPerTarget(1L)
                .maxLikes(0L)
                .maxPagesPerTarget(1L)
                .maxPosts(0L)
                .maxQuotes(0L)
                .maxReplies(0L)
                .maxRetweets(0L)
                .mediaType(ExtractionEstimateCostParams.MediaType.IMAGES)
                .mentioning("example_user")
                .minAccountAgeDays(0L)
                .minBookmarks(0L)
                .minFaves(10L)
                .minFollowers(0L)
                .minFollowing(0L)
                .minPosts(0L)
                .minQuotes(2L)
                .minReplies(3L)
                .minRetweets(5L)
                .minViews(0L)
                .nativeRetweets(true)
                .near("near")
                .news(true)
                .overlapMode(true)
                .place("96683cc9126741d1")
                .placeCountry("US")
                .pointRadius("-73.99 40.73 25mi")
                .queryType(ExtractionEstimateCostParams.QueryType.LATEST)
                .quotes(ExtractionEstimateCostParams.Quotes.INCLUDE)
                .quotesOfTweetId("1234567890")
                .addRelationTarget(
                    ExtractionEstimateCostParams.RelationTarget.builder()
                        .relation(
                            ExtractionEstimateCostParams.RelationTarget.Relation.COMMUNITY_MEMBERS
                        )
                        .value("x")
                        .build()
                )
                .replies(ExtractionEstimateCostParams.Replies.INCLUDE)
                .resultsLimit(1000L)
                .retweets(ExtractionEstimateCostParams.Retweets.EXCLUDE)
                .retweetsOfTweetId("1234567890")
                .safe(true)
                .scope(ExtractionEstimateCostParams.Scope.ALL)
                .addSearchQuery("string")
                .searchQuery("AI trends 2025")
                .sinceDate(LocalDate.parse("2025-01-01"))
                .sinceId("sinceId")
                .sinceTime(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .sort(ExtractionEstimateCostParams.Sort.RELEVANCE)
                .source("source")
                .startCursor("x")
                .targetCommunityId("1500000000000000000")
                .addTargetCommunityId("string")
                .targetListId("1234567890")
                .addTargetListId("string")
                .addTarget("string")
                .targetSpaceId("1vOGwMdBqpwGB")
                .targetTweetId("1234567890")
                .addTargetTweetId("string")
                .targetUsername("elonmusk")
                .addTargetUsername("string")
                .toUser("openai")
                .untilDate(LocalDate.parse("2025-12-31"))
                .untilTime(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .url("example.com")
                .usernameContains("usernameContains")
                .verifiedOnly(false)
                .verifiedType("verifiedType")
                .within("within")
                .withinTime("withinTime")
                .build()

        val body = params._body()

        assertThat(body.toolType())
            .isEqualTo(ExtractionEstimateCostParams.ToolType.FOLLOWER_EXPLORER)
        assertThat(body.advancedQuery()).contains("min_faves:100")
        assertThat(body.anyWords()).contains("ChatGPT AI model")
        assertThat(body.bioContains()).contains("bioContains")
        assertThat(body.blueVerifiedOnly()).contains(true)
        assertThat(body.boundingBox()).contains("-74.1 40.6 -73.9 40.8")
        assertThat(body.cardName()).contains("cardName")
        assertThat(body.cashtags()).contains("\$TSLA \$NVDA")
        assertThat(body.collectionStrategy())
            .contains(ExtractionEstimateCostParams.CollectionStrategy.AUTO)
        assertThat(body.conversationId()).contains("1234567890")
        assertThat(body.dedupeAcrossTargets()).contains(true)
        assertThat(body.dedupeMode()).contains(ExtractionEstimateCostParams.DedupeMode.NONE)
        assertThat(body.exactPhrase()).contains("artificial intelligence")
        assertThat(body.excludeOriginalAuthor()).contains(true)
        assertThat(body.excludeSource()).contains("excludeSource")
        assertThat(body.excludeWords()).contains("spam")
        assertThat(body.fromUser()).contains("nasa")
        assertThat(body.geocode()).contains("geocode")
        assertThat(body.hashtags()).contains("#AI startups")
        assertThat(body.hasLocation()).contains(true)
        assertThat(body.hasMediaOnly()).contains(true)
        assertThat(body.hasWebsite()).contains(true)
        assertThat(body.includeOriginalPost()).contains(true)
        assertThat(body.includeSearchTerms()).contains(true)
        assertThat(body.includeTargetMetadata()).contains(true)
        assertThat(body.inReplyToTweetId()).contains("1234567890")
        assertThat(body.language()).contains("en")
        assertThat(body.listId()).contains("1234567890")
        assertThat(body.locationContains()).contains("locationContains")
        assertThat(body.maxDepth()).contains(1L)
        assertThat(body.maxFollowers()).contains(0L)
        assertThat(body.maxFollowing()).contains(0L)
        assertThat(body.maxId()).contains("maxId")
        assertThat(body.maxItemsPerTarget()).contains(1L)
        assertThat(body.maxLikes()).contains(0L)
        assertThat(body.maxPagesPerTarget()).contains(1L)
        assertThat(body.maxPosts()).contains(0L)
        assertThat(body.maxQuotes()).contains(0L)
        assertThat(body.maxReplies()).contains(0L)
        assertThat(body.maxRetweets()).contains(0L)
        assertThat(body.mediaType()).contains(ExtractionEstimateCostParams.MediaType.IMAGES)
        assertThat(body.mentioning()).contains("example_user")
        assertThat(body.minAccountAgeDays()).contains(0L)
        assertThat(body.minBookmarks()).contains(0L)
        assertThat(body.minFaves()).contains(10L)
        assertThat(body.minFollowers()).contains(0L)
        assertThat(body.minFollowing()).contains(0L)
        assertThat(body.minPosts()).contains(0L)
        assertThat(body.minQuotes()).contains(2L)
        assertThat(body.minReplies()).contains(3L)
        assertThat(body.minRetweets()).contains(5L)
        assertThat(body.minViews()).contains(0L)
        assertThat(body.nativeRetweets()).contains(true)
        assertThat(body.near()).contains("near")
        assertThat(body.news()).contains(true)
        assertThat(body.overlapMode()).contains(true)
        assertThat(body.place()).contains("96683cc9126741d1")
        assertThat(body.placeCountry()).contains("US")
        assertThat(body.pointRadius()).contains("-73.99 40.73 25mi")
        assertThat(body.queryType()).contains(ExtractionEstimateCostParams.QueryType.LATEST)
        assertThat(body.quotes()).contains(ExtractionEstimateCostParams.Quotes.INCLUDE)
        assertThat(body.quotesOfTweetId()).contains("1234567890")
        assertThat(body.relationTargets().getOrNull())
            .containsExactly(
                ExtractionEstimateCostParams.RelationTarget.builder()
                    .relation(
                        ExtractionEstimateCostParams.RelationTarget.Relation.COMMUNITY_MEMBERS
                    )
                    .value("x")
                    .build()
            )
        assertThat(body.replies()).contains(ExtractionEstimateCostParams.Replies.INCLUDE)
        assertThat(body.resultsLimit()).contains(1000L)
        assertThat(body.retweets()).contains(ExtractionEstimateCostParams.Retweets.EXCLUDE)
        assertThat(body.retweetsOfTweetId()).contains("1234567890")
        assertThat(body.safe()).contains(true)
        assertThat(body.scope()).contains(ExtractionEstimateCostParams.Scope.ALL)
        assertThat(body.searchQueries().getOrNull()).containsExactly("string")
        assertThat(body.searchQuery()).contains("AI trends 2025")
        assertThat(body.sinceDate()).contains(LocalDate.parse("2025-01-01"))
        assertThat(body.sinceId()).contains("sinceId")
        assertThat(body.sinceTime())
            .contains(
                ExtractionEstimateCostParams.SinceTime.ofOffsetDate(
                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                )
            )
        assertThat(body.sort()).contains(ExtractionEstimateCostParams.Sort.RELEVANCE)
        assertThat(body.source()).contains("source")
        assertThat(body.startCursor()).contains("x")
        assertThat(body.targetCommunityId()).contains("1500000000000000000")
        assertThat(body.targetCommunityIds().getOrNull()).containsExactly("string")
        assertThat(body.targetListId()).contains("1234567890")
        assertThat(body.targetListIds().getOrNull()).containsExactly("string")
        assertThat(body.targets().getOrNull())
            .containsExactly(ExtractionEstimateCostParams.Target.ofString("string"))
        assertThat(body.targetSpaceId()).contains("1vOGwMdBqpwGB")
        assertThat(body.targetTweetId()).contains("1234567890")
        assertThat(body.targetTweetIds().getOrNull()).containsExactly("string")
        assertThat(body.targetUsername()).contains("elonmusk")
        assertThat(body.targetUsernames().getOrNull()).containsExactly("string")
        assertThat(body.toUser()).contains("openai")
        assertThat(body.untilDate()).contains(LocalDate.parse("2025-12-31"))
        assertThat(body.untilTime())
            .contains(
                ExtractionEstimateCostParams.UntilTime.ofOffsetDate(
                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                )
            )
        assertThat(body.url()).contains("example.com")
        assertThat(body.usernameContains()).contains("usernameContains")
        assertThat(body.verifiedOnly()).contains(false)
        assertThat(body.verifiedType()).contains("verifiedType")
        assertThat(body.within()).contains("within")
        assertThat(body.withinTime()).contains("withinTime")
    }

    @Test
    fun bodyWithoutOptionalFields() {
        val params =
            ExtractionEstimateCostParams.builder()
                .toolType(ExtractionEstimateCostParams.ToolType.FOLLOWER_EXPLORER)
                .build()

        val body = params._body()

        assertThat(body.toolType())
            .isEqualTo(ExtractionEstimateCostParams.ToolType.FOLLOWER_EXPLORER)
    }
}
