// File generated from our OpenAPI spec by Stainless.

package com.x_twitter_scraper.api.models.x.users.follow

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.x_twitter_scraper.api.core.JsonValue
import com.x_twitter_scraper.api.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class FollowDeleteAllResponseTest {

    @Test
    fun create() {
        val followDeleteAllResponse =
            FollowDeleteAllResponse.builder()
                .id("12345")
                .account(
                    FollowDeleteAllResponse.Account.builder().id("42").username("example").build()
                )
                .action(FollowDeleteAllResponse.Action.LIKE)
                .billing(
                    FollowDeleteAllResponse.Billing.builder()
                        .charged(true)
                        .chargedCredits("10")
                        .plannedCredits("10")
                        .status(FollowDeleteAllResponse.Billing.Status.CHARGED)
                        .build()
                )
                .charged(true)
                .chargedCredits("10")
                .nextAction(
                    FollowDeleteAllResponse.NextAction.builder()
                        .type(FollowDeleteAllResponse.NextAction.Type.POLL)
                        .afterMs(2000L)
                        .requiresNewIdempotencyKey(true)
                        .url("/api/v1/x/write-actions/12345")
                        .build()
                )
                .pollAfterMs(null)
                .request(
                    FollowDeleteAllResponse.Request.builder()
                        .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                        .payload(
                            FollowDeleteAllResponse.Request.Payload.builder()
                                .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .result(
                    FollowDeleteAllResponse.Result.builder()
                        .id("9876543210")
                        .state("liked")
                        .type(FollowDeleteAllResponse.Result.Type.STATE_CHANGE)
                        .build()
                )
                .retryable(false)
                .safeToRetry(false)
                .sendDispatched(true)
                .status(FollowDeleteAllResponse.Status.SUCCESS)
                .statusUrl("/api/v1/x/write-actions/12345")
                .success(true)
                .target(
                    FollowDeleteAllResponse.Target.builder()
                        .id("9876543210")
                        .type(FollowDeleteAllResponse.Target.Type.TWEET)
                        .build()
                )
                .targetId("9876543210")
                .terminal(true)
                .writeActionId("12345")
                .communityId("3456789012")
                .communityName("Builders")
                .completedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmationAttempts(1L)
                .confirmationCheckedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .createdAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .details(
                    FollowDeleteAllResponse.Details.builder()
                        .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                        .build()
                )
                .error("x_write_ambiguous")
                .expiresAt(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
                .idempotent(false)
                .media(
                    FollowDeleteAllResponse.Media.builder()
                        .putAdditionalProperty("count", JsonValue.from("bar"))
                        .putAdditionalProperty("kind", JsonValue.from("bar"))
                        .build()
                )
                .mediaId("2345678901")
                .mediaUrl("https://media.xquik.com/example.jpg")
                .message("Invalid input. Check request fields.")
                .messageId("1234567890")
                .requestHash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                .requestId("01JZ8R7QSC9QKT0V7JX4M2A6B8")
                .resultId("9876543210")
                .sendDispatchedAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .tweetId("9876543210")
                .updatedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .build()

        assertThat(followDeleteAllResponse.id()).isEqualTo("12345")
        assertThat(followDeleteAllResponse.account())
            .contains(
                FollowDeleteAllResponse.Account.builder().id("42").username("example").build()
            )
        assertThat(followDeleteAllResponse.action()).isEqualTo(FollowDeleteAllResponse.Action.LIKE)
        assertThat(followDeleteAllResponse.billing())
            .isEqualTo(
                FollowDeleteAllResponse.Billing.builder()
                    .charged(true)
                    .chargedCredits("10")
                    .plannedCredits("10")
                    .status(FollowDeleteAllResponse.Billing.Status.CHARGED)
                    .build()
            )
        assertThat(followDeleteAllResponse.charged()).isEqualTo(true)
        assertThat(followDeleteAllResponse.chargedCredits()).isEqualTo("10")
        assertThat(followDeleteAllResponse.nextAction())
            .contains(
                FollowDeleteAllResponse.NextAction.builder()
                    .type(FollowDeleteAllResponse.NextAction.Type.POLL)
                    .afterMs(2000L)
                    .requiresNewIdempotencyKey(true)
                    .url("/api/v1/x/write-actions/12345")
                    .build()
            )
        assertThat(followDeleteAllResponse.pollAfterMs()).isEmpty
        assertThat(followDeleteAllResponse.request())
            .isEqualTo(
                FollowDeleteAllResponse.Request.builder()
                    .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                    .payload(
                        FollowDeleteAllResponse.Request.Payload.builder()
                            .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                            .build()
                    )
                    .build()
            )
        assertThat(followDeleteAllResponse.result())
            .contains(
                FollowDeleteAllResponse.Result.builder()
                    .id("9876543210")
                    .state("liked")
                    .type(FollowDeleteAllResponse.Result.Type.STATE_CHANGE)
                    .build()
            )
        assertThat(followDeleteAllResponse.retryable()).isEqualTo(false)
        assertThat(followDeleteAllResponse.safeToRetry()).isEqualTo(false)
        assertThat(followDeleteAllResponse.sendDispatched()).isEqualTo(true)
        assertThat(followDeleteAllResponse.status())
            .isEqualTo(FollowDeleteAllResponse.Status.SUCCESS)
        assertThat(followDeleteAllResponse.statusUrl()).isEqualTo("/api/v1/x/write-actions/12345")
        assertThat(followDeleteAllResponse.success()).isEqualTo(true)
        assertThat(followDeleteAllResponse.target())
            .contains(
                FollowDeleteAllResponse.Target.builder()
                    .id("9876543210")
                    .type(FollowDeleteAllResponse.Target.Type.TWEET)
                    .build()
            )
        assertThat(followDeleteAllResponse.targetId()).contains("9876543210")
        assertThat(followDeleteAllResponse.terminal()).isEqualTo(true)
        assertThat(followDeleteAllResponse.writeActionId()).isEqualTo("12345")
        assertThat(followDeleteAllResponse.communityId()).contains("3456789012")
        assertThat(followDeleteAllResponse.communityName()).contains("Builders")
        assertThat(followDeleteAllResponse.completedAt())
            .contains(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(followDeleteAllResponse.confirmationAttempts()).contains(1L)
        assertThat(followDeleteAllResponse.confirmationCheckedAt())
            .contains(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(followDeleteAllResponse.confirmedAt())
            .contains(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(followDeleteAllResponse.createdAt())
            .contains(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
        assertThat(followDeleteAllResponse.details())
            .contains(
                FollowDeleteAllResponse.Details.builder()
                    .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                    .build()
            )
        assertThat(followDeleteAllResponse.error()).contains("x_write_ambiguous")
        assertThat(followDeleteAllResponse.expiresAt())
            .contains(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
        assertThat(followDeleteAllResponse.idempotent()).contains(false)
        assertThat(followDeleteAllResponse.media())
            .contains(
                FollowDeleteAllResponse.Media.builder()
                    .putAdditionalProperty("count", JsonValue.from("bar"))
                    .putAdditionalProperty("kind", JsonValue.from("bar"))
                    .build()
            )
        assertThat(followDeleteAllResponse.mediaId()).contains("2345678901")
        assertThat(followDeleteAllResponse.mediaUrl())
            .contains("https://media.xquik.com/example.jpg")
        assertThat(followDeleteAllResponse.message())
            .contains("Invalid input. Check request fields.")
        assertThat(followDeleteAllResponse.messageId()).contains("1234567890")
        assertThat(followDeleteAllResponse.requestHash())
            .contains("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
        assertThat(followDeleteAllResponse.requestId()).contains("01JZ8R7QSC9QKT0V7JX4M2A6B8")
        assertThat(followDeleteAllResponse.resultId()).contains("9876543210")
        assertThat(followDeleteAllResponse.sendDispatchedAt())
            .contains(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
        assertThat(followDeleteAllResponse.tweetId()).contains("9876543210")
        assertThat(followDeleteAllResponse.updatedAt())
            .contains(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val followDeleteAllResponse =
            FollowDeleteAllResponse.builder()
                .id("12345")
                .account(
                    FollowDeleteAllResponse.Account.builder().id("42").username("example").build()
                )
                .action(FollowDeleteAllResponse.Action.LIKE)
                .billing(
                    FollowDeleteAllResponse.Billing.builder()
                        .charged(true)
                        .chargedCredits("10")
                        .plannedCredits("10")
                        .status(FollowDeleteAllResponse.Billing.Status.CHARGED)
                        .build()
                )
                .charged(true)
                .chargedCredits("10")
                .nextAction(
                    FollowDeleteAllResponse.NextAction.builder()
                        .type(FollowDeleteAllResponse.NextAction.Type.POLL)
                        .afterMs(2000L)
                        .requiresNewIdempotencyKey(true)
                        .url("/api/v1/x/write-actions/12345")
                        .build()
                )
                .pollAfterMs(null)
                .request(
                    FollowDeleteAllResponse.Request.builder()
                        .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                        .payload(
                            FollowDeleteAllResponse.Request.Payload.builder()
                                .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .result(
                    FollowDeleteAllResponse.Result.builder()
                        .id("9876543210")
                        .state("liked")
                        .type(FollowDeleteAllResponse.Result.Type.STATE_CHANGE)
                        .build()
                )
                .retryable(false)
                .safeToRetry(false)
                .sendDispatched(true)
                .status(FollowDeleteAllResponse.Status.SUCCESS)
                .statusUrl("/api/v1/x/write-actions/12345")
                .success(true)
                .target(
                    FollowDeleteAllResponse.Target.builder()
                        .id("9876543210")
                        .type(FollowDeleteAllResponse.Target.Type.TWEET)
                        .build()
                )
                .targetId("9876543210")
                .terminal(true)
                .writeActionId("12345")
                .communityId("3456789012")
                .communityName("Builders")
                .completedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmationAttempts(1L)
                .confirmationCheckedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .createdAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .details(
                    FollowDeleteAllResponse.Details.builder()
                        .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                        .build()
                )
                .error("x_write_ambiguous")
                .expiresAt(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
                .idempotent(false)
                .media(
                    FollowDeleteAllResponse.Media.builder()
                        .putAdditionalProperty("count", JsonValue.from("bar"))
                        .putAdditionalProperty("kind", JsonValue.from("bar"))
                        .build()
                )
                .mediaId("2345678901")
                .mediaUrl("https://media.xquik.com/example.jpg")
                .message("Invalid input. Check request fields.")
                .messageId("1234567890")
                .requestHash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                .requestId("01JZ8R7QSC9QKT0V7JX4M2A6B8")
                .resultId("9876543210")
                .sendDispatchedAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .tweetId("9876543210")
                .updatedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .build()

        val roundtrippedFollowDeleteAllResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(followDeleteAllResponse),
                jacksonTypeRef<FollowDeleteAllResponse>(),
            )

        assertThat(roundtrippedFollowDeleteAllResponse).isEqualTo(followDeleteAllResponse)
    }
}
