// File generated from our OpenAPI spec by Stainless.

package com.x_twitter_scraper.api.models.x.media

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.x_twitter_scraper.api.core.JsonValue
import com.x_twitter_scraper.api.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class MediaUploadResponseTest {

    @Test
    fun create() {
        val mediaUploadResponse =
            MediaUploadResponse.builder()
                .id("12345")
                .account(MediaUploadResponse.Account.builder().id("42").username("example").build())
                .action(MediaUploadResponse.Action.LIKE)
                .billing(
                    MediaUploadResponse.Billing.builder()
                        .charged(true)
                        .chargedCredits("10")
                        .plannedCredits("10")
                        .status(MediaUploadResponse.Billing.Status.CHARGED)
                        .build()
                )
                .charged(true)
                .chargedCredits("10")
                .nextAction(
                    MediaUploadResponse.NextAction.builder()
                        .type(MediaUploadResponse.NextAction.Type.POLL)
                        .afterMs(2000L)
                        .requiresNewIdempotencyKey(true)
                        .url("/api/v1/x/write-actions/12345")
                        .build()
                )
                .pollAfterMs(null)
                .request(
                    MediaUploadResponse.Request.builder()
                        .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                        .payload(
                            MediaUploadResponse.Request.Payload.builder()
                                .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .result(
                    MediaUploadResponse.Result.builder()
                        .id("9876543210")
                        .state("liked")
                        .type(MediaUploadResponse.Result.Type.STATE_CHANGE)
                        .build()
                )
                .retryable(false)
                .safeToRetry(false)
                .sendDispatched(true)
                .status(MediaUploadResponse.Status.SUCCESS)
                .statusUrl("/api/v1/x/write-actions/12345")
                .success(true)
                .target(
                    MediaUploadResponse.Target.builder()
                        .id("9876543210")
                        .type(MediaUploadResponse.Target.Type.TWEET)
                        .build()
                )
                .targetId("9876543210")
                .terminal(true)
                .writeActionId("12345")
                .communityId("3456789012")
                .communityName("Builders")
                .completedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmationAttempts(1L)
                .confirmationCheckedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .createdAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .details(
                    MediaUploadResponse.Details.builder()
                        .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                        .build()
                )
                .error("x_write_ambiguous")
                .expiresAt(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
                .idempotent(false)
                .media(
                    MediaUploadResponse.Media.builder()
                        .putAdditionalProperty("count", JsonValue.from("bar"))
                        .putAdditionalProperty("kind", JsonValue.from("bar"))
                        .build()
                )
                .mediaId("2345678901")
                .mediaUrl("https://media.xquik.com/example.jpg")
                .message("Invalid input. Check request fields.")
                .messageId("1234567890")
                .requestHash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                .requestId("01JZ8R7QSC9QKT0V7JX4M2A6B8")
                .resultId("9876543210")
                .sendDispatchedAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .tweetId("9876543210")
                .updatedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .build()

        assertThat(mediaUploadResponse.id()).isEqualTo("12345")
        assertThat(mediaUploadResponse.account())
            .contains(MediaUploadResponse.Account.builder().id("42").username("example").build())
        assertThat(mediaUploadResponse.action()).isEqualTo(MediaUploadResponse.Action.LIKE)
        assertThat(mediaUploadResponse.billing())
            .isEqualTo(
                MediaUploadResponse.Billing.builder()
                    .charged(true)
                    .chargedCredits("10")
                    .plannedCredits("10")
                    .status(MediaUploadResponse.Billing.Status.CHARGED)
                    .build()
            )
        assertThat(mediaUploadResponse.charged()).isEqualTo(true)
        assertThat(mediaUploadResponse.chargedCredits()).isEqualTo("10")
        assertThat(mediaUploadResponse.nextAction())
            .contains(
                MediaUploadResponse.NextAction.builder()
                    .type(MediaUploadResponse.NextAction.Type.POLL)
                    .afterMs(2000L)
                    .requiresNewIdempotencyKey(true)
                    .url("/api/v1/x/write-actions/12345")
                    .build()
            )
        assertThat(mediaUploadResponse.pollAfterMs()).isEmpty
        assertThat(mediaUploadResponse.request())
            .isEqualTo(
                MediaUploadResponse.Request.builder()
                    .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                    .payload(
                        MediaUploadResponse.Request.Payload.builder()
                            .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                            .build()
                    )
                    .build()
            )
        assertThat(mediaUploadResponse.result())
            .contains(
                MediaUploadResponse.Result.builder()
                    .id("9876543210")
                    .state("liked")
                    .type(MediaUploadResponse.Result.Type.STATE_CHANGE)
                    .build()
            )
        assertThat(mediaUploadResponse.retryable()).isEqualTo(false)
        assertThat(mediaUploadResponse.safeToRetry()).isEqualTo(false)
        assertThat(mediaUploadResponse.sendDispatched()).isEqualTo(true)
        assertThat(mediaUploadResponse.status()).isEqualTo(MediaUploadResponse.Status.SUCCESS)
        assertThat(mediaUploadResponse.statusUrl()).isEqualTo("/api/v1/x/write-actions/12345")
        assertThat(mediaUploadResponse.success()).isEqualTo(true)
        assertThat(mediaUploadResponse.target())
            .contains(
                MediaUploadResponse.Target.builder()
                    .id("9876543210")
                    .type(MediaUploadResponse.Target.Type.TWEET)
                    .build()
            )
        assertThat(mediaUploadResponse.targetId()).contains("9876543210")
        assertThat(mediaUploadResponse.terminal()).isEqualTo(true)
        assertThat(mediaUploadResponse.writeActionId()).isEqualTo("12345")
        assertThat(mediaUploadResponse.communityId()).contains("3456789012")
        assertThat(mediaUploadResponse.communityName()).contains("Builders")
        assertThat(mediaUploadResponse.completedAt())
            .contains(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(mediaUploadResponse.confirmationAttempts()).contains(1L)
        assertThat(mediaUploadResponse.confirmationCheckedAt())
            .contains(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(mediaUploadResponse.confirmedAt())
            .contains(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(mediaUploadResponse.createdAt())
            .contains(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
        assertThat(mediaUploadResponse.details())
            .contains(
                MediaUploadResponse.Details.builder()
                    .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                    .build()
            )
        assertThat(mediaUploadResponse.error()).contains("x_write_ambiguous")
        assertThat(mediaUploadResponse.expiresAt())
            .contains(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
        assertThat(mediaUploadResponse.idempotent()).contains(false)
        assertThat(mediaUploadResponse.media())
            .contains(
                MediaUploadResponse.Media.builder()
                    .putAdditionalProperty("count", JsonValue.from("bar"))
                    .putAdditionalProperty("kind", JsonValue.from("bar"))
                    .build()
            )
        assertThat(mediaUploadResponse.mediaId()).contains("2345678901")
        assertThat(mediaUploadResponse.mediaUrl()).contains("https://media.xquik.com/example.jpg")
        assertThat(mediaUploadResponse.message()).contains("Invalid input. Check request fields.")
        assertThat(mediaUploadResponse.messageId()).contains("1234567890")
        assertThat(mediaUploadResponse.requestHash())
            .contains("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
        assertThat(mediaUploadResponse.requestId()).contains("01JZ8R7QSC9QKT0V7JX4M2A6B8")
        assertThat(mediaUploadResponse.resultId()).contains("9876543210")
        assertThat(mediaUploadResponse.sendDispatchedAt())
            .contains(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
        assertThat(mediaUploadResponse.tweetId()).contains("9876543210")
        assertThat(mediaUploadResponse.updatedAt())
            .contains(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val mediaUploadResponse =
            MediaUploadResponse.builder()
                .id("12345")
                .account(MediaUploadResponse.Account.builder().id("42").username("example").build())
                .action(MediaUploadResponse.Action.LIKE)
                .billing(
                    MediaUploadResponse.Billing.builder()
                        .charged(true)
                        .chargedCredits("10")
                        .plannedCredits("10")
                        .status(MediaUploadResponse.Billing.Status.CHARGED)
                        .build()
                )
                .charged(true)
                .chargedCredits("10")
                .nextAction(
                    MediaUploadResponse.NextAction.builder()
                        .type(MediaUploadResponse.NextAction.Type.POLL)
                        .afterMs(2000L)
                        .requiresNewIdempotencyKey(true)
                        .url("/api/v1/x/write-actions/12345")
                        .build()
                )
                .pollAfterMs(null)
                .request(
                    MediaUploadResponse.Request.builder()
                        .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                        .payload(
                            MediaUploadResponse.Request.Payload.builder()
                                .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .result(
                    MediaUploadResponse.Result.builder()
                        .id("9876543210")
                        .state("liked")
                        .type(MediaUploadResponse.Result.Type.STATE_CHANGE)
                        .build()
                )
                .retryable(false)
                .safeToRetry(false)
                .sendDispatched(true)
                .status(MediaUploadResponse.Status.SUCCESS)
                .statusUrl("/api/v1/x/write-actions/12345")
                .success(true)
                .target(
                    MediaUploadResponse.Target.builder()
                        .id("9876543210")
                        .type(MediaUploadResponse.Target.Type.TWEET)
                        .build()
                )
                .targetId("9876543210")
                .terminal(true)
                .writeActionId("12345")
                .communityId("3456789012")
                .communityName("Builders")
                .completedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmationAttempts(1L)
                .confirmationCheckedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .createdAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .details(
                    MediaUploadResponse.Details.builder()
                        .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                        .build()
                )
                .error("x_write_ambiguous")
                .expiresAt(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
                .idempotent(false)
                .media(
                    MediaUploadResponse.Media.builder()
                        .putAdditionalProperty("count", JsonValue.from("bar"))
                        .putAdditionalProperty("kind", JsonValue.from("bar"))
                        .build()
                )
                .mediaId("2345678901")
                .mediaUrl("https://media.xquik.com/example.jpg")
                .message("Invalid input. Check request fields.")
                .messageId("1234567890")
                .requestHash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                .requestId("01JZ8R7QSC9QKT0V7JX4M2A6B8")
                .resultId("9876543210")
                .sendDispatchedAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .tweetId("9876543210")
                .updatedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .build()

        val roundtrippedMediaUploadResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(mediaUploadResponse),
                jacksonTypeRef<MediaUploadResponse>(),
            )

        assertThat(roundtrippedMediaUploadResponse).isEqualTo(mediaUploadResponse)
    }
}
