// SPDX-FileCopyrightText: 2026 Xquik contributors
//
// SPDX-License-Identifier: Apache-2.0

// File generated from our OpenAPI spec by Stainless.

package com.x_twitter_scraper.api.models.x.profile

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.x_twitter_scraper.api.core.JsonValue
import com.x_twitter_scraper.api.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class ProfileUpdateBannerResponseTest {

    @Test
    fun create() {
        val profileUpdateBannerResponse =
            ProfileUpdateBannerResponse.builder()
                .id("12345")
                .account(
                    ProfileUpdateBannerResponse.Account.builder()
                        .id("42")
                        .username("example")
                        .build()
                )
                .action(ProfileUpdateBannerResponse.Action.LIKE)
                .billing(
                    ProfileUpdateBannerResponse.Billing.builder()
                        .charged(true)
                        .chargedCredits("10")
                        .plannedCredits("10")
                        .status(ProfileUpdateBannerResponse.Billing.Status.CHARGED)
                        .build()
                )
                .charged(true)
                .chargedCredits("10")
                .nextAction(
                    ProfileUpdateBannerResponse.NextAction.builder()
                        .type(ProfileUpdateBannerResponse.NextAction.Type.POLL)
                        .afterMs(2000L)
                        .requiresNewIdempotencyKey(true)
                        .url("/api/v1/x/write-actions/12345")
                        .build()
                )
                .pollAfterMs(null)
                .request(
                    ProfileUpdateBannerResponse.Request.builder()
                        .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                        .payload(
                            ProfileUpdateBannerResponse.Request.Payload.builder()
                                .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .result(
                    ProfileUpdateBannerResponse.Result.builder()
                        .id("9876543210")
                        .state("liked")
                        .type(ProfileUpdateBannerResponse.Result.Type.STATE_CHANGE)
                        .build()
                )
                .retryable(false)
                .safeToRetry(false)
                .sendDispatched(true)
                .status(ProfileUpdateBannerResponse.Status.SUCCESS)
                .statusUrl("/api/v1/x/write-actions/12345")
                .success(true)
                .target(
                    ProfileUpdateBannerResponse.Target.builder()
                        .id("9876543210")
                        .type(ProfileUpdateBannerResponse.Target.Type.TWEET)
                        .build()
                )
                .targetId("9876543210")
                .terminal(true)
                .writeActionId("12345")
                .communityId("3456789012")
                .communityName("Builders")
                .completedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmationAttempts(1L)
                .confirmationCheckedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .createdAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .details(
                    ProfileUpdateBannerResponse.Details.builder()
                        .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                        .build()
                )
                .error("x_write_ambiguous")
                .expiresAt(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
                .idempotent(false)
                .media(
                    ProfileUpdateBannerResponse.Media.builder()
                        .putAdditionalProperty("count", JsonValue.from("bar"))
                        .putAdditionalProperty("kind", JsonValue.from("bar"))
                        .build()
                )
                .mediaId("2345678901")
                .mediaUrl("https://media.xquik.com/example.jpg")
                .message("Invalid input. Check request fields.")
                .messageId("1234567890")
                .requestHash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                .requestId("01JZ8R7QSC9QKT0V7JX4M2A6B8")
                .resultId("9876543210")
                .sendDispatchedAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .tweetId("9876543210")
                .updatedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .build()

        assertThat(profileUpdateBannerResponse.id()).isEqualTo("12345")
        assertThat(profileUpdateBannerResponse.account())
            .contains(
                ProfileUpdateBannerResponse.Account.builder().id("42").username("example").build()
            )
        assertThat(profileUpdateBannerResponse.action())
            .isEqualTo(ProfileUpdateBannerResponse.Action.LIKE)
        assertThat(profileUpdateBannerResponse.billing())
            .isEqualTo(
                ProfileUpdateBannerResponse.Billing.builder()
                    .charged(true)
                    .chargedCredits("10")
                    .plannedCredits("10")
                    .status(ProfileUpdateBannerResponse.Billing.Status.CHARGED)
                    .build()
            )
        assertThat(profileUpdateBannerResponse.charged()).isEqualTo(true)
        assertThat(profileUpdateBannerResponse.chargedCredits()).isEqualTo("10")
        assertThat(profileUpdateBannerResponse.nextAction())
            .contains(
                ProfileUpdateBannerResponse.NextAction.builder()
                    .type(ProfileUpdateBannerResponse.NextAction.Type.POLL)
                    .afterMs(2000L)
                    .requiresNewIdempotencyKey(true)
                    .url("/api/v1/x/write-actions/12345")
                    .build()
            )
        assertThat(profileUpdateBannerResponse.pollAfterMs()).isEmpty
        assertThat(profileUpdateBannerResponse.request())
            .isEqualTo(
                ProfileUpdateBannerResponse.Request.builder()
                    .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                    .payload(
                        ProfileUpdateBannerResponse.Request.Payload.builder()
                            .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                            .build()
                    )
                    .build()
            )
        assertThat(profileUpdateBannerResponse.result())
            .contains(
                ProfileUpdateBannerResponse.Result.builder()
                    .id("9876543210")
                    .state("liked")
                    .type(ProfileUpdateBannerResponse.Result.Type.STATE_CHANGE)
                    .build()
            )
        assertThat(profileUpdateBannerResponse.retryable()).isEqualTo(false)
        assertThat(profileUpdateBannerResponse.safeToRetry()).isEqualTo(false)
        assertThat(profileUpdateBannerResponse.sendDispatched()).isEqualTo(true)
        assertThat(profileUpdateBannerResponse.status())
            .isEqualTo(ProfileUpdateBannerResponse.Status.SUCCESS)
        assertThat(profileUpdateBannerResponse.statusUrl())
            .isEqualTo("/api/v1/x/write-actions/12345")
        assertThat(profileUpdateBannerResponse.success()).isEqualTo(true)
        assertThat(profileUpdateBannerResponse.target())
            .contains(
                ProfileUpdateBannerResponse.Target.builder()
                    .id("9876543210")
                    .type(ProfileUpdateBannerResponse.Target.Type.TWEET)
                    .build()
            )
        assertThat(profileUpdateBannerResponse.targetId()).contains("9876543210")
        assertThat(profileUpdateBannerResponse.terminal()).isEqualTo(true)
        assertThat(profileUpdateBannerResponse.writeActionId()).isEqualTo("12345")
        assertThat(profileUpdateBannerResponse.communityId()).contains("3456789012")
        assertThat(profileUpdateBannerResponse.communityName()).contains("Builders")
        assertThat(profileUpdateBannerResponse.completedAt())
            .contains(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(profileUpdateBannerResponse.confirmationAttempts()).contains(1L)
        assertThat(profileUpdateBannerResponse.confirmationCheckedAt())
            .contains(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(profileUpdateBannerResponse.confirmedAt())
            .contains(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
        assertThat(profileUpdateBannerResponse.createdAt())
            .contains(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
        assertThat(profileUpdateBannerResponse.details())
            .contains(
                ProfileUpdateBannerResponse.Details.builder()
                    .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                    .build()
            )
        assertThat(profileUpdateBannerResponse.error()).contains("x_write_ambiguous")
        assertThat(profileUpdateBannerResponse.expiresAt())
            .contains(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
        assertThat(profileUpdateBannerResponse.idempotent()).contains(false)
        assertThat(profileUpdateBannerResponse.media())
            .contains(
                ProfileUpdateBannerResponse.Media.builder()
                    .putAdditionalProperty("count", JsonValue.from("bar"))
                    .putAdditionalProperty("kind", JsonValue.from("bar"))
                    .build()
            )
        assertThat(profileUpdateBannerResponse.mediaId()).contains("2345678901")
        assertThat(profileUpdateBannerResponse.mediaUrl())
            .contains("https://media.xquik.com/example.jpg")
        assertThat(profileUpdateBannerResponse.message())
            .contains("Invalid input. Check request fields.")
        assertThat(profileUpdateBannerResponse.messageId()).contains("1234567890")
        assertThat(profileUpdateBannerResponse.requestHash())
            .contains("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
        assertThat(profileUpdateBannerResponse.requestId()).contains("01JZ8R7QSC9QKT0V7JX4M2A6B8")
        assertThat(profileUpdateBannerResponse.resultId()).contains("9876543210")
        assertThat(profileUpdateBannerResponse.sendDispatchedAt())
            .contains(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
        assertThat(profileUpdateBannerResponse.tweetId()).contains("9876543210")
        assertThat(profileUpdateBannerResponse.updatedAt())
            .contains(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val profileUpdateBannerResponse =
            ProfileUpdateBannerResponse.builder()
                .id("12345")
                .account(
                    ProfileUpdateBannerResponse.Account.builder()
                        .id("42")
                        .username("example")
                        .build()
                )
                .action(ProfileUpdateBannerResponse.Action.LIKE)
                .billing(
                    ProfileUpdateBannerResponse.Billing.builder()
                        .charged(true)
                        .chargedCredits("10")
                        .plannedCredits("10")
                        .status(ProfileUpdateBannerResponse.Billing.Status.CHARGED)
                        .build()
                )
                .charged(true)
                .chargedCredits("10")
                .nextAction(
                    ProfileUpdateBannerResponse.NextAction.builder()
                        .type(ProfileUpdateBannerResponse.NextAction.Type.POLL)
                        .afterMs(2000L)
                        .requiresNewIdempotencyKey(true)
                        .url("/api/v1/x/write-actions/12345")
                        .build()
                )
                .pollAfterMs(null)
                .request(
                    ProfileUpdateBannerResponse.Request.builder()
                        .hash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                        .payload(
                            ProfileUpdateBannerResponse.Request.Payload.builder()
                                .putAdditionalProperty("tweet_id", JsonValue.from("bar"))
                                .build()
                        )
                        .build()
                )
                .result(
                    ProfileUpdateBannerResponse.Result.builder()
                        .id("9876543210")
                        .state("liked")
                        .type(ProfileUpdateBannerResponse.Result.Type.STATE_CHANGE)
                        .build()
                )
                .retryable(false)
                .safeToRetry(false)
                .sendDispatched(true)
                .status(ProfileUpdateBannerResponse.Status.SUCCESS)
                .statusUrl("/api/v1/x/write-actions/12345")
                .success(true)
                .target(
                    ProfileUpdateBannerResponse.Target.builder()
                        .id("9876543210")
                        .type(ProfileUpdateBannerResponse.Target.Type.TWEET)
                        .build()
                )
                .targetId("9876543210")
                .terminal(true)
                .writeActionId("12345")
                .communityId("3456789012")
                .communityName("Builders")
                .completedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmationAttempts(1L)
                .confirmationCheckedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .confirmedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .createdAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .details(
                    ProfileUpdateBannerResponse.Details.builder()
                        .putAdditionalProperty("suggestion", JsonValue.from("bar"))
                        .build()
                )
                .error("x_write_ambiguous")
                .expiresAt(OffsetDateTime.parse("2026-07-22T05:00:00Z"))
                .idempotent(false)
                .media(
                    ProfileUpdateBannerResponse.Media.builder()
                        .putAdditionalProperty("count", JsonValue.from("bar"))
                        .putAdditionalProperty("kind", JsonValue.from("bar"))
                        .build()
                )
                .mediaId("2345678901")
                .mediaUrl("https://media.xquik.com/example.jpg")
                .message("Invalid input. Check request fields.")
                .messageId("1234567890")
                .requestHash("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
                .requestId("01JZ8R7QSC9QKT0V7JX4M2A6B8")
                .resultId("9876543210")
                .sendDispatchedAt(OffsetDateTime.parse("2026-07-21T05:00:00Z"))
                .tweetId("9876543210")
                .updatedAt(OffsetDateTime.parse("2026-07-21T05:00:02Z"))
                .build()

        val roundtrippedProfileUpdateBannerResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(profileUpdateBannerResponse),
                jacksonTypeRef<ProfileUpdateBannerResponse>(),
            )

        assertThat(roundtrippedProfileUpdateBannerResponse).isEqualTo(profileUpdateBannerResponse)
    }
}
